### ISSUE TITLE
NullPointerException after Undo Jam Start at beginning of game

### ISSUE THREAD

**Issue by signe** [rollerderby/scoreboard#242]
Version @ 1bbc3859f

Rare issue, but I discovered this while testing —

1. Start new game
2. Start Jam
3. Undo Start Jam
4. Start Jam
    * Scoreboard immediately becomes unresponsive and jam never starts
    * Checking the console shows a NullPointerException

```
java.lang.NullPointerException
	at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl.setNeighbors(NumberedScoreBoardEventProviderImpl.java:118)
	at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl.<init>(NumberedScoreBoardEventProviderImpl.java:19)
	at com.carolinarollergirls.scoreboard.core.impl.JamImpl.<init>(JamImpl.java:27)
	at com.carolinarollergirls.scoreboard.core.impl.JamImpl.<init>(JamImpl.java:23)
	at com.carolinarollergirls.scoreboard.core.impl.ScoreBoardImpl.advanceUpcomingJam(ScoreBoardImpl.java:208)
	at com.carolinarollergirls.scoreboard.core.impl.ScoreBoardImpl._startJam(ScoreBoardImpl.java:403)
	at com.carolinarollergirls.scoreboard.core.impl.ScoreBoardImpl.startJam(ScoreBoardImpl.java:266)
	at com.carolinarollergirls.scoreboard.core.impl.ScoreBoardImpl.execute(ScoreBoardImpl.java:100)
	at com.carolinarollergirls.scoreboard.xml.ScoreBoardXmlConverter.process(ScoreBoardXmlConverter.java:117)
	at com.carolinarollergirls.scoreboard.xml.ScoreBoardXmlConverter.processDocument(ScoreBoardXmlConverter.java:86)
	at com.carolinarollergirls.scoreboard.xml.XmlScoreBoard.mergeDocument(XmlScoreBoard.java:122)
	at com.carolinarollergirls.scoreboard.jetty.XmlScoreBoardServlet.set(XmlScoreBoardServlet.java:74)
	at com.carolinarollergirls.scoreboard.jetty.XmlScoreBoardServlet.doPost(XmlScoreBoardServlet.java:135)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1317)
	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:944)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1005)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by brian-brazil** [comment]
This was fixed.
