### ISSUE TITLE
NPE in SkaterImpl.getFielding on Start New Game

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#425]
See https://www.facebook.com/groups/126006504596245/permalink/701799783683578/

On start new game with the attached save, there's the following NPE:

```
Error handling JSON message: java.lang.NullPointerException
java.lang.NullPointerException
        at com.carolinarollergirls.scoreboard.core.impl.SkaterImpl.getFielding(SkaterImpl.java:160)
        at com.carolinarollergirls.scoreboard.core.impl.SkaterImpl.getRole(SkaterImpl.java:190)
        at com.carolinarollergirls.scoreboard.core.impl.SkaterImpl.itemAdded(SkaterImpl.java:126)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl._itemAdded(ScoreBoardEventProviderImpl.java:421)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.add(ScoreBoardEventProviderImpl.java:407)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:72)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:69)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:69)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:69)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:69)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:69)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl.setNeighbors(NumberedScoreBoardEventProviderImpl.java:110)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl.moveToNumber(NumberedScoreBoardEventProviderImpl.java:87)
        at com.carolinarollergirls.scoreboard.core.impl.PenaltyImpl.valueChanged(PenaltyImpl.java:61)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl._valueChanged(ScoreBoardEventProviderImpl.java:344)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl._valueChanged(NumberedScoreBoardEventProviderImpl.java:74)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:324)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:298)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.unlink(ScoreBoardEventProviderImpl.java:168)
        at com.carolinarollergirls.scoreboard.event.NumberedScoreBoardEventProviderImpl.unlink(NumberedScoreBoardEventProviderImpl.java:47)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.unlink(ScoreBoardEventProviderImpl.java:161)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.unlink(ScoreBoardEventProviderImpl.java:153)
        at com.carolinarollergirls.scoreboard.core.impl.TeamImpl.itemRemoved(TeamImpl.java:190)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl._itemRemoved(ScoreBoardEventProviderImpl.java:466)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.remove(ScoreBoardEventProviderImpl.java:438)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.removeAll(ScoreBoardEventProviderImpl.java:473)
        at com.carolinarollergirls.scoreboard.core.impl.TeamImpl.reset(TeamImpl.java:215)
        at com.carolinarollergirls.scoreboard.core.impl.ScoreBoardImpl.reset(ScoreBoardImpl.java:193)
        at com.carolinarollergirls.scoreboard.jetty.WS$Conn$2.run(WS.java:141)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.runInBatch(ScoreBoardEventProviderImpl.java:120)
        at com.carolinarollergirls.scoreboard.jetty.WS$Conn.onMessage(WS.java:135)
        at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame(WebSocketConnectionRFC6455.java:850)
        at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext(WebSocketParserRFC6455.java:349)
        at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle(WebSocketConnectionRFC6455.java:225)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by brian-brazil** [comment]
Okay, github doesn't like .json so here it is with a different extension:

[scoreboard-0-secs-ago.txt](https://github.com/rollerderby/scoreboard/files/4080308/scoreboard-0-secs-ago.txt)

**Comment by spikenheimer** [comment]
in case it helps, i've attached another scoreboard json file that also causes this issue.
[erroringgamesave.json.txt](https://github.com/rollerderby/scoreboard/files/4289944/erroringgamesave.json.txt)

**Comment by frank-weinberg** [comment]
This appears to be fixed in current dev. At least it is no longer reproducible with the attached save.
