### ISSUE TITLE
Statsbook export gives Java error re: multiple cell comments

### ISSUE THREAD

**Issue by tdondich** [rollerderby/scoreboard#534]
When attempting to export with 5.0.4, the following bug is presented.

JSON file export is provided.

Exception in thread "Thread-29" java.lang.IllegalArgumentException: Multiple cell comments in one cell are not allowed, cell: G4
	at org.apache.poi.xssf.usermodel.XSSFDrawing.createCellComment(XSSFDrawing.java:390)
	at org.apache.poi.xssf.usermodel.XSSFDrawing.createCellComment(XSSFDrawing.java:79)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.setComment(StatsbookExporter.java:664)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.setCell(StatsbookExporter.java:633)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.fillInitialTrip(StatsbookExporter.java:495)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.fillScoreTeamJam(StatsbookExporter.java:479)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.fillJam(StatsbookExporter.java:455)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.fillScoreLineupsAndClock(StatsbookExporter.java:380)
	at com.carolinarollergirls.scoreboard.utils.StatsbookExporter.run(StatsbookExporter.java:109)

**Comment by tdondich** [comment]
[STATS-2022-09-10_SinCityRollerDerby_vs_RoughDiamondRollerDerby.json.zip](https://github.com/rollerderby/scoreboard/files/9594895/STATS-2022-09-10_SinCityRollerDerby_vs_RoughDiamondRollerDerby.json.zip)

**Comment by frank-weinberg** [comment]
I found the source of the problem. Fix will be in 5.0.7 which I hope to get released today.
