### ISSUE TITLE
[BUG] Crash on v2025.3: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Togimaro** [rollerderby/scoreboard#811]
**Describe the bug**
Yesterday during the french tournament we encountered an exception leading to a hard crash of CRG 2025.3, during a jam all the software suddenly stopped working (clocks stopped, score was unable to be updated, the whole deal).
Upon relaunch of the server the game completely disappeared from the data and the scoreboard showed a previous game result.

The logs showed only this exception a bunch of times:
```
Error handling JSON message: java.lang.IllegalStateException: Timer already cancelled.
java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Unknown Source)
        at java.util.Timer.schedule(Unknown Source)
        at com.carolinarollergirls.scoreboard.core.game.TeamImpl.computeValue(TeamImpl.java:212)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl._computeValue(ScoreBoardEventProviderImpl.java:476)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.set(ScoreBoardEventProviderImpl.java:456)
        at com.carolinarollergirls.scoreboard.json.ScoreBoardJSONSetter$ValueSet.process(ScoreBoardJSONSetter.java:361)
        at com.carolinarollergirls.scoreboard.json.ScoreBoardJSONSetter.set(ScoreBoardJSONSetter.java:269)
        at com.carolinarollergirls.scoreboard.jetty.WS$ScoreBoardWebSocket$1.run(WS.java:161)
        at com.carolinarollergirls.scoreboard.event.ScoreBoardEventProviderImpl.runInBatch(ScoreBoardEventProviderImpl.java:120)
        at com.carolinarollergirls.scoreboard.jetty.WS$ScoreBoardWebSocket.onMessage(WS.java:158)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:301)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:67)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:287)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:152)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:148)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:111)
        at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:169)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:90)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
        at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Unknown Source)
```
The save file doesn't contains any information about the game anymore.

**Screenshots**
The issue is visible on the replay https://www.youtube.com/live/TYZ4JnRlojs?t=23435s you can notice at 11:36 on the period clock everything stopped working.

**Version:**
CRG 2025.3

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 11
 - Browser: Chrome
 - Version: 131.0.6778.109 (Build officiel) (64 bits)

**Comment by frank-weinberg** [comment]
If I see that correctly in the video, on relaunch it went back to the last game of the previous day, not the previous game. That would indicate that autosave had not been working since the start of the day and presumably the other games of the day are also missing. Can you confirm this?

The exception also can only occur if the scoreboard did not start properly or was partially shut down for some reason. And since it occurred "a bunch of times" that would also point to something being broken with this scoreboard instance for a while.

If you say "the logs" are you referring to the Java window or the crg.log file? In the window earlier exceptions that could help identify the source of the problem may have scrolled out. In this case the file could be useful as they should still be in there.

PS: Kudos to the crew for getting the game running again relatively quickly after this worst case scenario of an error.

**Comment by Togimaro** [comment]
Yes the software rolled back to the morning state, the first two game of that day was now marked as prepared and the next two games was gone. There is no backup between the beginning of the first game and the crash.

[Here is the complete crg.log](https://github.com/user-attachments/files/18076790/crg.log) (there was multiple java.io.EOFException exception saturday, we had some corrupted XSLX due to a buggy USB drive but the game from sunday were imported correctly).

Weirdly enough in the log there is two :
```
Found existing autosave dir - skipping import
CRG ScoreBoard version v2025.3
Loaded auto-saved scoreboard from .\config\autosave\scoreboard-0-secs-ago.json
```
in a row after the welcome message without any reboot of the software, but without some timestamps it's hard to tell what happened (I didn't setup the computer that morning and don't know if it's a user error or not).

Ahah thanks, the statsbook importation was quite useful to rapidly resetup a fresh install.

**Comment by frank-weinberg** [comment]
> Weirdly enough in the log there is two [first part of startup] in a row

This may actually be the key, especially the fact that these are not followed by even one instance of the IP list. I was able to reproduce this part of the log by starting multiple instances in parallel - maybe that is what happened.
This would also explain the missing autosave data: When there are multiple instances of CRG running in the same folder, they will all run on the same autosave files. So each instance will once per 10s rotate all the existing files and add a new one. So presumably an instance that was inactive has written last and the latest file with the new data was scorebaord-10-secs-ago (or maybe scoreboard-20-secs-ago if there were three instances running). On startup the old set of autosave files is copied to config/autosave/backup/<timestamp> - the folder with the timestamp of restarting after the crash should have these files.
